name: 'delete-branch-package-versions'

description: 'An action to delete pre-release GH Package versions created for a specified branch'

inputs:
  github-token:
    description: 'An access token with the `packages:delete` and `packages:read` scopes that is authorized in the organization where the package versions to be deleted are.'
    required: true
  organization:
    description: 'The organization the packages were created in.  Defaults to github.context.repo.org if not provided.'
    required: false
  repository:
    description: 'The repo the packages were created in.  Defaults to github.context.repo.repo if not provided.'
    required: false
  branch-name:
    description: 'The branch name the packages were created with.  This is how package versions to delete are identified.'
    required: true
  package-type:
    description: 'The type of package where versions will be deleted.  Can be one of npm, maven, rubygems, nuget, docker or container.'
    required: true
  package-names:
    description: 'The names of the packages that versions will be deleted from. Expects one value or a comma separated list (e.g. package1, package2). If not specified, it will default to all of the packages in the current repo.'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
